#!/bin/sh
if [ ! -e src ]; then echo "Not in aspinwall source directory"; exit 1; fi

if [ -e output ]; then rm -r output; fi

set -e
meson --prefix=/tmp/aspinwall-shell . output
meson compile -C output
meson install -C output

Xnest :3 +extension XFIXES +extension X-Resource &
xnest_pid=$!

export DISPLAY=:3
export GSETTINGS_SCHEMA_DIR=/tmp/aspinwall-shell/share/glib-2.0/schemas
export GTK_DEBUG=interactive
export ASPINWALL_WIDGET_DIR=/tmp/aspinwall-launcher/share/aspinwall/widgets

herbstluftwm -c /tmp/aspinwall-shell/share/aspinwall-shell/x11/autostart &
herbst_pid=$!

trap_ctrlc() {
	kill $xnest_pid
	kill $herbst_pid
}

trap trap_ctrlc INT

wait
