#!/bin/sh
if [ ! -e src ]; then echo "Not in aspinwall source directory"; exit 1; fi

if [ -e output ]; then rm -r output; fi

set -e
meson --prefix=/tmp/aspinwall-shell . output
meson compile -C output
meson install -C output
GSETTINGS_SCHEMA_DIR=/tmp/aspinwall-shell/share/glib-2.0/schemas GTK_DEBUG=interactive /tmp/aspinwall-shell/bin/aspinwall-shell
